package com.billooms.outlineeditor;

import com.billooms.cutpoints.CutPoint;
import com.billooms.cutpoints.CutPoints;
import com.billooms.cutpoints.SpiralCut;
import javax.swing.JPanel;
import org.openide.explorer.ExplorerManager;
import org.openide.nodes.Node;
import org.openide.windows.WindowManager;

/**
 * A panel to prompt for data to convert a spiral to individual CutPoints.
 *
 * @author Bill Ooms. Copyright 2015 Studio of Bill Ooms. All rights reserved.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
public class MacroSpiralPanel extends JPanel {

  /* Default spacing. */
  private final static double DEFAULT_SPACING = 0.1;
  /* Minimum spacing. */
  private final static double MIN_SPACE = 0.010;
  
  /** All instances share one ExplorerManager. */
  private static ExplorerManager em = null; 
  /** CutPoint manager. */
  private final CutPoints cutPtMgr;
  
  /** The selected SpiralCut to expand. */
  private SpiralCut editPt;
  /** Total length of the spiral on the surface. */
  private double spiralLength = 0.0;
  /** Number of additional points inserted (between start and end points). */
  private int nInserts;	

  /**
   * Creates new form MacroSpiralPanel.
   *
   * @throws java.lang.Exception
   */
  public MacroSpiralPanel() throws Exception {
    initComponents();
    
    if (em == null) {
      em = ((ExplorerManager.Provider) WindowManager.getDefault().findTopComponent("DataNavigatorTopComponent")).getExplorerManager();
    }
    Node rootNode = em.getRootContext();
    cutPtMgr = rootNode.getLookup().lookup(CutPoints.class);

    for (CutPoint cc : cutPtMgr.getAll()) {
      if (cc instanceof SpiralCut) {
        numberCombo.addItem(cc.getNum());
      }
    }
    if (numberCombo.getItemCount() == 0) {
      throw new Exception("No spiral cutpoints in list");
    }
    numberCombo.setSelectedIndex(0);

    update();
  }

  /**
   * Calculate new lengths along the curve and update display.
   */
  private void update() {
    editPt = (SpiralCut) cutPtMgr.get((Integer) numberCombo.getSelectedItem());
    spiralLabel.setText(editPt.getSpiral().getStyle().getDisplayName());
    spiralLength = editPt.getTotalDistance();
    totalField.setValue(spiralLength);

    nInserts = (int) Math.round(spiralLength / ((Number) spaceField.getValue()).doubleValue());
    nInserts = nInserts - 1;
    nPointsField.setValue(nInserts);
  }

  /**
   * Make the points and insert them in the cutList.
   */
  public void makePoints() {
    if ((nInserts == 0) || (spiralLength == 0.0)) {
      return;
    }
    cutPtMgr.spiralToPoints(editPt, nInserts);
  }

  /** This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel6 = new javax.swing.JLabel();
    numberCombo = new javax.swing.JComboBox();
    spiralLabel = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    totalField = new javax.swing.JFormattedTextField();
    jLabel2 = new javax.swing.JLabel();
    spaceField = new javax.swing.JFormattedTextField();
    jLabel3 = new javax.swing.JLabel();
    nPointsField = new javax.swing.JFormattedTextField();

    jLabel6.setText("CutPoint #:");

    numberCombo.setToolTipText("Select which spiral to use");
    numberCombo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changePoint(evt);
      }
    });

    spiralLabel.setText(org.openide.util.NbBundle.getMessage(MacroSpiralPanel.class, "MacroSpiralPanel.spiralLabel.text")); // NOI18N

    jLabel1.setText(org.openide.util.NbBundle.getMessage(MacroSpiralPanel.class, "MacroSpiralPanel.jLabel1.text")); // NOI18N

    totalField.setEditable(false);
    totalField.setColumns(5);
    totalField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.000"))));

    jLabel2.setText("Approximate Spacing:");

    spaceField.setColumns(5);
    spaceField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.000"))));
    spaceField.setToolTipText("Set approximate spacing of inserted points");
    spaceField.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
    spaceField.setValue(DEFAULT_SPACING);
    spaceField.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
      public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
        scrollSpacing(evt);
      }
    });
    spaceField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      public void propertyChange(java.beans.PropertyChangeEvent evt) {
        changeSpacing(evt);
      }
    });

    jLabel3.setText("Number of inserted points:");

    nPointsField.setEditable(false);
    nPointsField.setColumns(5);
    nPointsField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(numberCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(spiralLabel))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(spaceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(nPointsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(numberCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(spiralLabel))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(spaceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(nPointsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

	private void scrollSpacing(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_scrollSpacing
      double s = ((Number) spaceField.getValue()).doubleValue() - 0.01 * evt.getWheelRotation();
      s = Math.max(MIN_SPACE, s);
      spaceField.setValue(s);
	}//GEN-LAST:event_scrollSpacing

	private void changeSpacing(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_changeSpacing
      update();
	}//GEN-LAST:event_changeSpacing

  private void changePoint(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePoint
    if (numberCombo.isFocusOwner()) {
      update();
    }
  }//GEN-LAST:event_changePoint


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JFormattedTextField nPointsField;
  private javax.swing.JComboBox numberCombo;
  private javax.swing.JFormattedTextField spaceField;
  private javax.swing.JLabel spiralLabel;
  private javax.swing.JFormattedTextField totalField;
  // End of variables declaration//GEN-END:variables

}
