package com.billooms.outlineeditor;

import javax.swing.JPanel;

/**
 * Panel for entering information about vertical offset of curves.
 *
 * @author Bill Ooms. Copyright 2015 Studio of Bill Ooms. All rights reserved.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
public class OffsetPanel extends JPanel {

  /** Construct new OffsetPanel */
  public OffsetPanel() {
    initComponents();
    posField.setValue(0.0);
    posField.setEnabled(false);
  }

  /** This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        curveCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        topBottomCombo = new javax.swing.JComboBox();
        zeroPosCombo = new javax.swing.JComboBox();
        posField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        dirCombo = new javax.swing.JComboBox();

        setEnabled(false);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(OffsetPanel.class, "OffsetPanel.jLabel1.text")); // NOI18N

        curveCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inside Curve", "OutSide Curve", "Cutter Curve" }));

        jLabel2.setText(org.openide.util.NbBundle.getMessage(OffsetPanel.class, "OffsetPanel.jLabel2.text")); // NOI18N

        topBottomCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Top", "Bottom" }));

        zeroPosCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Zero", "Position" }));
        zeroPosCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeZeroPos(evt);
            }
        });

        posField.setColumns(5);
        posField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.000"))));
        posField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        posField.setText(org.openide.util.NbBundle.getMessage(OffsetPanel.class, "OffsetPanel.posField.text")); // NOI18N
        posField.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        jLabel3.setText(org.openide.util.NbBundle.getMessage(OffsetPanel.class, "OffsetPanel.jLabel3.text")); // NOI18N

        dirCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vertically", "Perpendicular" }));
        dirCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeDirection(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dirCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(topBottomCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(curveCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zeroPosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dirCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topBottomCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(curveCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zeroPosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(posField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void changeZeroPos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeZeroPos
      switch (zeroPosCombo.getSelectedIndex()) {
        case 0:
          posField.setValue(0.0);
          posField.setEnabled(false);
          break;
        case 1:
          posField.setEnabled(true);
      }
	}//GEN-LAST:event_changeZeroPos

	private void changeDirection(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeDirection
      switch (dirCombo.getSelectedIndex()) {
        case 0:
          topBottomCombo.setEnabled(true);
          curveCombo.setEnabled(true);
          zeroPosCombo.setEnabled(true);
          break;
        case 1:
          topBottomCombo.setEnabled(false);
          curveCombo.setEnabled(false);
          zeroPosCombo.setSelectedIndex(1);
          zeroPosCombo.setEnabled(false);
          posField.setEnabled(true);
          break;
      }
	}//GEN-LAST:event_changeDirection

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JComboBox curveCombo;
    protected javax.swing.JComboBox dirCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    protected javax.swing.JFormattedTextField posField;
    protected javax.swing.JComboBox topBottomCombo;
    protected javax.swing.JComboBox zeroPosCombo;
    // End of variables declaration//GEN-END:variables
}
