package com.billooms.cornlatheprefs;

import javax.swing.JPanel;
import org.openide.util.NbPreferences;

/**
 * Preference panel.
 *
 * @author Bill Ooms. Copyright 2015 Studio of Bill Ooms. All rights reserved.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
final class COrnLathePanel extends JPanel {

  private final COrnLatheOptionsPanelController controller;

  COrnLathePanel(COrnLatheOptionsPanelController controller) {
    this.controller = controller;
    initComponents();
    // TODO listen to changes in form fields and call controller.changed()
  }

  /** This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    engPhaseButton = new javax.swing.JRadioButton();
    fracPhaseButton = new javax.swing.JRadioButton();

    setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(COrnLathePanel.class, "COrnLathePanel.border.title"))); // NOI18N

    buttonGroup1.add(engPhaseButton);
    engPhaseButton.setSelected(true);
    org.openide.awt.Mnemonics.setLocalizedText(engPhaseButton, org.openide.util.NbBundle.getMessage(COrnLathePanel.class, "COrnLathePanel.engPhaseButton.text")); // NOI18N

    buttonGroup1.add(fracPhaseButton);
    org.openide.awt.Mnemonics.setLocalizedText(fracPhaseButton, org.openide.util.NbBundle.getMessage(COrnLathePanel.class, "COrnLathePanel.fracPhaseButton.text")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(engPhaseButton)
          .addComponent(fracPhaseButton))
        .addContainerGap(54, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(engPhaseButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fracPhaseButton)
        .addContainerGap(41, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  void load() {
    fracPhaseButton.setSelected(NbPreferences.forModule(COrnLathePanel.class).getBoolean("fracPhase", false));
  }

  void store() {
    NbPreferences.forModule(COrnLathePanel.class).putBoolean("fracPhase", fracPhaseButton.isSelected());
  }

  boolean valid() {
    // TODO check whether form is consistent and complete
    return true;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JRadioButton engPhaseButton;
  private javax.swing.JRadioButton fracPhaseButton;
  // End of variables declaration//GEN-END:variables
}
